configuration: Release

image: Visual Studio 2017

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
          Update-AppveyorBuild -Version "3.3.0-ci.$($env:APPVEYOR_BUILD_NUMBER)+sha.$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

cache:
  - '%LocalAppData%\NuGet\v3-cache -> **\*.csproj'

before_build:
  - dotnet restore --verbosity quiet

build:
  verbosity: quiet

test_script:
  - nuget install OpenCover -x -Verbosity quiet
  - OpenCover\tools\OpenCover.Console.exe -oldstyle -returntargetcode -register:user -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test --configuration Release --verbosity quiet --no-build src\Ninject.Extensions.ChildKernel.Test" -filter:"+[Ninject.Extensions.ChildKernel]*" -excludebyattribute:*.ExcludeFromCodeCoverage*;*.Obsolete* -output:"Ninject.Extensions.ChildKernel_coverage.xml"
  - nuget install Codecov -x -Verbosity quiet
  - Codecov\tools\codecov.exe -f "Ninject.Extensions.ChildKernel_coverage.xml"

artifacts:
  - path: 'src\**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: Sn05A/FiUAlID5v31uaf5EZuYCSo4frLONtrCY+cwY265dU2JUZsl2+sjVeLQyz/
  on:
    appveyor_repo_tag: true
